strategy:
  matrix:
    linux_node_10:
      imageName: 'ubuntu-16.04'
      node_version: 10.x
    mac_node_10:
      imageName: 'macos-10.13'
      node_version: 10.x
    windows_node_10:
      imageName: 'vs2017-win2016'
      node_version: 10.x
    linux_node_12:
      imageName: 'ubuntu-16.04'
      node_version: 12.x
    mac_node_12:
      imageName: 'macos-10.13'
      node_version: 12.x
    windows_node_12:
      imageName: 'vs2017-win2016'
      node_version: 12.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js

  - bash: npm install
    displayName: Install dependencies

  - bash: npm test
    displayName: Test
